
import "./globals.scss";
import './assets/styles/variables.scss'
import MainHeader from "../../components/header/MainHeader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>       
        <MainHeader/>
        {children}
      </body>
    </html>
  );
}
